[package]
name = "dynv6-updater"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
nix = { version = "0.29.0", features = ["net"] }
reqwest = { version = "0.12.8", default-features = false, features = ["http2", "rustls-tls-native-roots", "blocking"] }
